# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import model_pb2 as model__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in model_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServiceStub(object):
    """Model service for handling model downloads and status
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnsureModelDownloaded = channel.unary_stream(
                '/model_express.model.ModelService/EnsureModelDownloaded',
                request_serializer=model__pb2.ModelDownloadRequest.SerializeToString,
                response_deserializer=model__pb2.ModelStatusUpdate.FromString,
                _registered_method=True)
        self.StreamModelFiles = channel.unary_stream(
                '/model_express.model.ModelService/StreamModelFiles',
                request_serializer=model__pb2.ModelFilesRequest.SerializeToString,
                response_deserializer=model__pb2.FileChunk.FromString,
                _registered_method=True)
        self.ListModelFiles = channel.unary_unary(
                '/model_express.model.ModelService/ListModelFiles',
                request_serializer=model__pb2.ModelFilesRequest.SerializeToString,
                response_deserializer=model__pb2.ModelFileList.FromString,
                _registered_method=True)
        self.DeleteModel = channel.unary_unary(
                '/model_express.model.ModelService/DeleteModel',
                request_serializer=model__pb2.DeleteModelRequest.SerializeToString,
                response_deserializer=model__pb2.DeleteModelResponse.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """Model service for handling model downloads and status
    """

    def EnsureModelDownloaded(self, request, context):
        """Ensure a model is downloaded and stream status updates until completion
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamModelFiles(self, request, context):
        """Stream model files from server to client (used when shared storage is disabled)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModelFiles(self, request, context):
        """Get list of files for a model (useful for resumable transfers)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteModel(self, request, context):
        """Delete a model record from the server-side registry (used by `model clear`)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnsureModelDownloaded': grpc.unary_stream_rpc_method_handler(
                    servicer.EnsureModelDownloaded,
                    request_deserializer=model__pb2.ModelDownloadRequest.FromString,
                    response_serializer=model__pb2.ModelStatusUpdate.SerializeToString,
            ),
            'StreamModelFiles': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamModelFiles,
                    request_deserializer=model__pb2.ModelFilesRequest.FromString,
                    response_serializer=model__pb2.FileChunk.SerializeToString,
            ),
            'ListModelFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModelFiles,
                    request_deserializer=model__pb2.ModelFilesRequest.FromString,
                    response_serializer=model__pb2.ModelFileList.SerializeToString,
            ),
            'DeleteModel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteModel,
                    request_deserializer=model__pb2.DeleteModelRequest.FromString,
                    response_serializer=model__pb2.DeleteModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_express.model.ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model_express.model.ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Model service for handling model downloads and status
    """

    @staticmethod
    def EnsureModelDownloaded(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/model_express.model.ModelService/EnsureModelDownloaded',
            model__pb2.ModelDownloadRequest.SerializeToString,
            model__pb2.ModelStatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamModelFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/model_express.model.ModelService/StreamModelFiles',
            model__pb2.ModelFilesRequest.SerializeToString,
            model__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModelFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.model.ModelService/ListModelFiles',
            model__pb2.ModelFilesRequest.SerializeToString,
            model__pb2.ModelFileList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.model.ModelService/DeleteModel',
            model__pb2.DeleteModelRequest.SerializeToString,
            model__pb2.DeleteModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
