# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ include "modelexpress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "modelexpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 8001 }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if and .Values.metrics .Values.metrics.enabled .Values.metrics.service }}
    - port: {{ .Values.metrics.port | default 9401 }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "modelexpress.selectorLabels" . | nindent 4 }}
