# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import refit_pb2 as refit__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in refit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RefitServiceStub(object):
    """Control-plane metadata for RL weight publication. Object-storage-backed
    versions own one global object URI; worker-sharded versions advertise
    per-worker manifests.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateWeightVersion = channel.unary_unary(
                '/model_express.refit.RefitService/CreateWeightVersion',
                request_serializer=refit__pb2.CreateWeightVersionRequest.SerializeToString,
                response_deserializer=refit__pb2.CreateWeightVersionResponse.FromString,
                _registered_method=True)
        self.GetWeightVersion = channel.unary_unary(
                '/model_express.refit.RefitService/GetWeightVersion',
                request_serializer=refit__pb2.GetWeightVersionRequest.SerializeToString,
                response_deserializer=refit__pb2.GetWeightVersionResponse.FromString,
                _registered_method=True)
        self.DeleteWeightVersion = channel.unary_unary(
                '/model_express.refit.RefitService/DeleteWeightVersion',
                request_serializer=refit__pb2.DeleteWeightVersionRequest.SerializeToString,
                response_deserializer=refit__pb2.DeleteWeightVersionResponse.FromString,
                _registered_method=True)
        self.UpdateWeightVersionState = channel.unary_unary(
                '/model_express.refit.RefitService/UpdateWeightVersionState',
                request_serializer=refit__pb2.UpdateWeightVersionStateRequest.SerializeToString,
                response_deserializer=refit__pb2.UpdateWeightVersionStateResponse.FromString,
                _registered_method=True)
        self.RegisterWorker = channel.unary_unary(
                '/model_express.refit.RefitService/RegisterWorker',
                request_serializer=refit__pb2.RegisterWorkerRequest.SerializeToString,
                response_deserializer=refit__pb2.RegisterWorkerResponse.FromString,
                _registered_method=True)
        self.CreateWeightVersionShard = channel.unary_unary(
                '/model_express.refit.RefitService/CreateWeightVersionShard',
                request_serializer=refit__pb2.CreateWeightVersionShardRequest.SerializeToString,
                response_deserializer=refit__pb2.CreateWeightVersionShardResponse.FromString,
                _registered_method=True)
        self.ListWeightVersionShards = channel.unary_unary(
                '/model_express.refit.RefitService/ListWeightVersionShards',
                request_serializer=refit__pb2.ListWeightVersionShardsRequest.SerializeToString,
                response_deserializer=refit__pb2.ListWeightVersionShardsResponse.FromString,
                _registered_method=True)
        self.DeleteWeightVersionShard = channel.unary_unary(
                '/model_express.refit.RefitService/DeleteWeightVersionShard',
                request_serializer=refit__pb2.DeleteWeightVersionShardRequest.SerializeToString,
                response_deserializer=refit__pb2.DeleteWeightVersionShardResponse.FromString,
                _registered_method=True)
        self.RegisterVersionLease = channel.unary_unary(
                '/model_express.refit.RefitService/RegisterVersionLease',
                request_serializer=refit__pb2.RegisterVersionLeaseRequest.SerializeToString,
                response_deserializer=refit__pb2.RegisterVersionLeaseResponse.FromString,
                _registered_method=True)
        self.DeleteVersionLease = channel.unary_unary(
                '/model_express.refit.RefitService/DeleteVersionLease',
                request_serializer=refit__pb2.DeleteVersionLeaseRequest.SerializeToString,
                response_deserializer=refit__pb2.DeleteVersionLeaseResponse.FromString,
                _registered_method=True)


class RefitServiceServicer(object):
    """Control-plane metadata for RL weight publication. Object-storage-backed
    versions own one global object URI; worker-sharded versions advertise
    per-worker manifests.
    """

    def CreateWeightVersion(self, request, context):
        """External APIs: called by the RL framework orchestrator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeightVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWeightVersion(self, request, context):
        """Cancel a STAGING version or retire a READY version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWeightVersionState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterWorker(self, request, context):
        """Internal APIs: called by ModelExpress worker clients, not by the RL
        framework orchestrator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWeightVersionShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWeightVersionShards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteWeightVersionShard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterVersionLease(self, request, context):
        """A live lease protects the version source while a generator installs it.
        Re-registering the same lease owner renews its expiry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVersionLease(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RefitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateWeightVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWeightVersion,
                    request_deserializer=refit__pb2.CreateWeightVersionRequest.FromString,
                    response_serializer=refit__pb2.CreateWeightVersionResponse.SerializeToString,
            ),
            'GetWeightVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeightVersion,
                    request_deserializer=refit__pb2.GetWeightVersionRequest.FromString,
                    response_serializer=refit__pb2.GetWeightVersionResponse.SerializeToString,
            ),
            'DeleteWeightVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWeightVersion,
                    request_deserializer=refit__pb2.DeleteWeightVersionRequest.FromString,
                    response_serializer=refit__pb2.DeleteWeightVersionResponse.SerializeToString,
            ),
            'UpdateWeightVersionState': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWeightVersionState,
                    request_deserializer=refit__pb2.UpdateWeightVersionStateRequest.FromString,
                    response_serializer=refit__pb2.UpdateWeightVersionStateResponse.SerializeToString,
            ),
            'RegisterWorker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterWorker,
                    request_deserializer=refit__pb2.RegisterWorkerRequest.FromString,
                    response_serializer=refit__pb2.RegisterWorkerResponse.SerializeToString,
            ),
            'CreateWeightVersionShard': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWeightVersionShard,
                    request_deserializer=refit__pb2.CreateWeightVersionShardRequest.FromString,
                    response_serializer=refit__pb2.CreateWeightVersionShardResponse.SerializeToString,
            ),
            'ListWeightVersionShards': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWeightVersionShards,
                    request_deserializer=refit__pb2.ListWeightVersionShardsRequest.FromString,
                    response_serializer=refit__pb2.ListWeightVersionShardsResponse.SerializeToString,
            ),
            'DeleteWeightVersionShard': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteWeightVersionShard,
                    request_deserializer=refit__pb2.DeleteWeightVersionShardRequest.FromString,
                    response_serializer=refit__pb2.DeleteWeightVersionShardResponse.SerializeToString,
            ),
            'RegisterVersionLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterVersionLease,
                    request_deserializer=refit__pb2.RegisterVersionLeaseRequest.FromString,
                    response_serializer=refit__pb2.RegisterVersionLeaseResponse.SerializeToString,
            ),
            'DeleteVersionLease': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVersionLease,
                    request_deserializer=refit__pb2.DeleteVersionLeaseRequest.FromString,
                    response_serializer=refit__pb2.DeleteVersionLeaseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_express.refit.RefitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model_express.refit.RefitService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RefitService(object):
    """Control-plane metadata for RL weight publication. Object-storage-backed
    versions own one global object URI; worker-sharded versions advertise
    per-worker manifests.
    """

    @staticmethod
    def CreateWeightVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit.RefitService/CreateWeightVersion',
            refit__pb2.CreateWeightVersionRequest.SerializeToString,
            refit__pb2.CreateWeightVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWeightVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit.RefitService/GetWeightVersion',
            refit__pb2.GetWeightVersionRequest.SerializeToString,
            refit__pb2.GetWeightVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWeightVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit.RefitService/DeleteWeightVersion',
            refit__pb2.DeleteWeightVersionRequest.SerializeToString,
            refit__pb2.DeleteWeightVersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWeightVersionState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit.RefitService/UpdateWeightVersionState',
            refit__pb2.UpdateWeightVersionStateRequest.SerializeToString,
            refit__pb2.UpdateWeightVersionStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterWorker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit.RefitService/RegisterWorker',
            refit__pb2.RegisterWorkerRequest.SerializeToString,
            refit__pb2.RegisterWorkerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateWeightVersionShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit.RefitService/CreateWeightVersionShard',
            refit__pb2.CreateWeightVersionShardRequest.SerializeToString,
            refit__pb2.CreateWeightVersionShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWeightVersionShards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit.RefitService/ListWeightVersionShards',
            refit__pb2.ListWeightVersionShardsRequest.SerializeToString,
            refit__pb2.ListWeightVersionShardsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteWeightVersionShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit.RefitService/DeleteWeightVersionShard',
            refit__pb2.DeleteWeightVersionShardRequest.SerializeToString,
            refit__pb2.DeleteWeightVersionShardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterVersionLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit.RefitService/RegisterVersionLease',
            refit__pb2.RegisterVersionLeaseRequest.SerializeToString,
            refit__pb2.RegisterVersionLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVersionLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit.RefitService/DeleteVersionLease',
            refit__pb2.DeleteVersionLeaseRequest.SerializeToString,
            refit__pb2.DeleteVersionLeaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RefitWorkerServiceStub(object):
    """Internal worker-to-worker API. The generator fetches the small transfer
    manifest here; tensor bytes remain on the advertised data-plane transport.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWeightVersionShardManifest = channel.unary_unary(
                '/model_express.refit.RefitWorkerService/GetWeightVersionShardManifest',
                request_serializer=refit__pb2.GetWeightVersionShardManifestRequest.SerializeToString,
                response_deserializer=refit__pb2.GetWeightVersionShardManifestResponse.FromString,
                _registered_method=True)


class RefitWorkerServiceServicer(object):
    """Internal worker-to-worker API. The generator fetches the small transfer
    manifest here; tensor bytes remain on the advertised data-plane transport.
    """

    def GetWeightVersionShardManifest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RefitWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWeightVersionShardManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeightVersionShardManifest,
                    request_deserializer=refit__pb2.GetWeightVersionShardManifestRequest.FromString,
                    response_serializer=refit__pb2.GetWeightVersionShardManifestResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'model_express.refit.RefitWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('model_express.refit.RefitWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RefitWorkerService(object):
    """Internal worker-to-worker API. The generator fetches the small transfer
    manifest here; tensor bytes remain on the advertised data-plane transport.
    """

    @staticmethod
    def GetWeightVersionShardManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/model_express.refit.RefitWorkerService/GetWeightVersionShardManifest',
            refit__pb2.GetWeightVersionShardManifestRequest.SerializeToString,
            refit__pb2.GetWeightVersionShardManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
