# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: modelexpress-operator-metrics-tls
  name: modelexpress-operator-metrics
spec:
  ports:
  - name: https-metrics
    port: 8443
    targetPort: https-metrics
