# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "modelexpress-common"
description = "Shared utilities for Model Express client and server"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true

[features]
default = ["gcs", "tls-rustls"]
openssl = ["tls-native"]
gcs = ["dep:google-cloud-storage", "dep:rustls", "rustls/ring", "rustls/std"]
test-support = []
tls-native = [
    "dep:object_store",
    "dep:object-store-reqwest",
    "reqwest/native-tls",
    "object-store-reqwest/native-tls",
]
tls-rustls = [
    "dep:rustls",
    "dep:object_store",
    "dep:object-store-reqwest",
    "rustls/ring",
    "rustls/std",
    "object_store/ring",
    "reqwest/rustls-tls",
    "object-store-reqwest/rustls-no-provider",
]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = "0.9"
sha2 = { workspace = true }
thiserror = "2.0"
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
hf-hub = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
config = { workspace = true }
futures = { workspace = true }
jiff = { workspace = true }
reqwest = { workspace = true }
tempfile = { workspace = true }
object_store = { workspace = true, optional = true }
object-store-reqwest = { workspace = true, optional = true }
google-cloud-storage = { workspace = true, optional = true }
rustls = { workspace = true, optional = true }
crc32c = { workspace = true }
fd-lock = { workspace = true }

[dev-dependencies]
google-cloud-auth = { version = "1.7.0", default-features = false }
google-cloud-gax = { workspace = true }
wiremock = "0.6.5"

[build-dependencies]
tonic-build = { workspace = true }

[lints]
workspace = true
