# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: modelexpress
description: A Helm chart for ModelExpress - a AI model cache management service
type: application
version: 0.5.1
appVersion: "0.5.1"
keywords:
  - model-serving
  - ai
  - machine-learning
  - inference
home: https://github.com/ai-dynamo/modelexpress/
sources:
  - https://github.com/ai-dynamo/modelexpress/
icon: https://raw.githubusercontent.com/ai-dynamo/modelexpress/refs/heads/main/docs/images/model-express-key-visual.jpg
